import { Box, Button, HStack, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Box
          bg={`background`}
          border={`1px solid`}
          borderColor={`border`}
          p={`2rem`}
        >
          <Heading as={`h1`}>Home</Heading>
          <Text>This is a text component</Text>
          <HStack mt={3}>
            <Button bg={`complementary`}>Click</Button>
            <Button bg={`primary`}>Click</Button>
            <Button bg={`info`}>Click</Button>
            <Button bg={`warning`}>Click</Button>
            <Button bg={`success`}>Click</Button>
            <Button bg={`error`}>Click</Button>
          </HStack>
        </Box>
      </body>
    </>
  );
}
